export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUI_PROJETO = 'EXCLUI_PROJETO'

export const NOTIFICAR = 'NOTIFICAR'

export const ABRE_MODAL = 'ABRE_MODAL'
export const FECHA_MODAL = 'FECHA_MODAL'