export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUI_PROJETO = 'EXCLUI_PROJETO'
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'

export const SALVA_TAREFA = 'SALVA_TAREFA'
export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'
export const DEFINIR_TAREFAS_FILTRADAS = 'DEFINIR_TAREFAS_FILTRADAS'
export const ADICIONA_TAREFA = 'ADICIONA_TAREFA'
export const ALTERA_TAREFA = 'ALTERA_TAREFA'
export const EXCLUI_TAREFA = 'EXCLUI_TAREFA'

export const NOTIFICAR = 'NOTIFICAR'

export const ABRE_MODAL = 'ABRE_MODAL'
export const FECHA_MODAL = 'FECHA_MODAL'
